// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Limit struct {
	ID         int64
	Weekday    int64
	DurationMs int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Tracking struct {
	ID         int64
	DurationMs int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
