// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type DateLimit struct {
	ID           int64
	Date         time.Time
	LimitMinutes int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Tracking struct {
	ID          int64
	DurationSec int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WeekdayLimit struct {
	ID           int64
	Weekday      int64
	LimitMinutes int64
	UpdatedAt    time.Time
}
