// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addToDateLimitToday = `-- name: AddToDateLimitToday :one
INSERT INTO
    date_limits(limit_date, limit_minutes)
VALUES
    (DATE('now', 'localtime'), ?) ON CONFLICT(limit_date) DO
UPDATE
SET
    limit_minutes = limit_minutes + excluded.limit_minutes,
    updated_at = CURRENT_TIMESTAMP RETURNING id, limit_date, limit_minutes, created_at, updated_at
`

func (q *Queries) AddToDateLimitToday(ctx context.Context, limitMinutes int64) (DateLimit, error) {
	row := q.db.QueryRowContext(ctx, addToDateLimitToday, limitMinutes)
	var i DateLimit
	err := row.Scan(
		&i.ID,
		&i.LimitDate,
		&i.LimitMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDateLimitToday = `-- name: GetDateLimitToday :one
SELECT
    id, limit_date, limit_minutes, created_at, updated_at
FROM
    date_limits
WHERE
    DATE(limit_date) = DATE('now')
`

func (q *Queries) GetDateLimitToday(ctx context.Context) (DateLimit, error) {
	row := q.db.QueryRowContext(ctx, getDateLimitToday)
	var i DateLimit
	err := row.Scan(
		&i.ID,
		&i.LimitDate,
		&i.LimitMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDurationForToday = `-- name: GetDurationForToday :one
SELECT
    COUNT(id) AS count,
    SUM(duration_sec) AS total
FROM
    tracking
WHERE
    DATE(created_at, 'localtime') = DATE('now', 'localtime')
`

type GetDurationForTodayRow struct {
	Count int64
	Total sql.NullFloat64
}

func (q *Queries) GetDurationForToday(ctx context.Context) (GetDurationForTodayRow, error) {
	row := q.db.QueryRowContext(ctx, getDurationForToday)
	var i GetDurationForTodayRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}

const getWeekdayLimitToday = `-- name: GetWeekdayLimitToday :one
SELECT
    id, weekday, limit_minutes, updated_at
FROM
    weekday_limits
WHERE
    weekday = strftime('%w', 'now')
`

func (q *Queries) GetWeekdayLimitToday(ctx context.Context) (WeekdayLimit, error) {
	row := q.db.QueryRowContext(ctx, getWeekdayLimitToday)
	var i WeekdayLimit
	err := row.Scan(
		&i.ID,
		&i.Weekday,
		&i.LimitMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeekdayLimits = `-- name: GetWeekdayLimits :many
SELECT
    id, weekday, limit_minutes, updated_at
FROM
    weekday_limits
ORDER BY
    weekday
`

func (q *Queries) GetWeekdayLimits(ctx context.Context) ([]WeekdayLimit, error) {
	rows, err := q.db.QueryContext(ctx, getWeekdayLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeekdayLimit
	for rows.Next() {
		var i WeekdayLimit
		if err := rows.Scan(
			&i.ID,
			&i.Weekday,
			&i.LimitMinutes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newTrackingRecord = `-- name: NewTrackingRecord :one
INSERT INTO
    tracking(created_at, updated_at)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id, duration_sec, created_at, updated_at
`

func (q *Queries) NewTrackingRecord(ctx context.Context) (Tracking, error) {
	row := q.db.QueryRowContext(ctx, newTrackingRecord)
	var i Tracking
	err := row.Scan(
		&i.ID,
		&i.DurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeDateLimitToday = `-- name: RemoveDateLimitToday :exec
DELETE FROM
    date_limits
WHERE
    DATE(limit_date, 'localtime') = DATE('now', 'localtime')
`

func (q *Queries) RemoveDateLimitToday(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeDateLimitToday)
	return err
}

const setDateLimitToday = `-- name: SetDateLimitToday :one
INSERT INTO
    date_limits(limit_date, limit_minutes)
VALUES
    (DATE('now'), ?) ON CONFLICT(limit_date) DO
UPDATE
SET
    limit_minutes = excluded.limit_minutes,
    updated_at = CURRENT_TIMESTAMP RETURNING id, limit_date, limit_minutes, created_at, updated_at
`

func (q *Queries) SetDateLimitToday(ctx context.Context, limitMinutes int64) (DateLimit, error) {
	row := q.db.QueryRowContext(ctx, setDateLimitToday, limitMinutes)
	var i DateLimit
	err := row.Scan(
		&i.ID,
		&i.LimitDate,
		&i.LimitMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWeekdayLimits = `-- name: SetWeekdayLimits :exec
UPDATE
    weekday_limits
SET
    limit_minutes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    weekday IN (/*SLICE:weekdays*/?)
`

type SetWeekdayLimitsParams struct {
	LimitMinutes int64
	Weekdays     []int64
}

func (q *Queries) SetWeekdayLimits(ctx context.Context, arg SetWeekdayLimitsParams) error {
	query := setWeekdayLimits
	var queryParams []interface{}
	queryParams = append(queryParams, arg.LimitMinutes)
	if len(arg.Weekdays) > 0 {
		for _, v := range arg.Weekdays {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:weekdays*/?", strings.Repeat(",?", len(arg.Weekdays))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:weekdays*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateTrackingDuration = `-- name: UpdateTrackingDuration :one
UPDATE
    tracking
SET
    duration_sec = unixepoch('now', 'localtime') - unixepoch(created_at, 'localtime'),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ? RETURNING id, duration_sec, created_at, updated_at
`

func (q *Queries) UpdateTrackingDuration(ctx context.Context, id int64) (Tracking, error) {
	row := q.db.QueryRowContext(ctx, updateTrackingDuration, id)
	var i Tracking
	err := row.Scan(
		&i.ID,
		&i.DurationSec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
