// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const addTrackingRecordDuration = `-- name: AddTrackingRecordDuration :one
UPDATE
    tracking
SET
    duration_ms = duration_ms + ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ? RETURNING id, duration_ms, created_at, updated_at
`

type AddTrackingRecordDurationParams struct {
	DurationMs int64
	ID         int64
}

func (q *Queries) AddTrackingRecordDuration(ctx context.Context, arg AddTrackingRecordDurationParams) (Tracking, error) {
	row := q.db.QueryRowContext(ctx, addTrackingRecordDuration, arg.DurationMs, arg.ID)
	var i Tracking
	err := row.Scan(
		&i.ID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDurationForToday = `-- name: GetDurationForToday :one
SELECT
    COUNT(id) AS count,
    SUM(duration_ms) AS total
FROM
    tracking
WHERE
    DATE(created_at) = DATE('now')
`

type GetDurationForTodayRow struct {
	Count int64
	Total sql.NullFloat64
}

func (q *Queries) GetDurationForToday(ctx context.Context) (GetDurationForTodayRow, error) {
	row := q.db.QueryRowContext(ctx, getDurationForToday)
	var i GetDurationForTodayRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}

const getLimits = `-- name: GetLimits :many
SELECT
    id, weekday, limit_sec, created_at, updated_at
FROM
    limits
`

func (q *Queries) GetLimits(ctx context.Context) ([]Limit, error) {
	rows, err := q.db.QueryContext(ctx, getLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Limit
	for rows.Next() {
		var i Limit
		if err := rows.Scan(
			&i.ID,
			&i.Weekday,
			&i.LimitSec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrackingRecord = `-- name: InsertTrackingRecord :one
INSERT INTO
    tracking(created_at, updated_at)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id, duration_ms, created_at, updated_at
`

func (q *Queries) InsertTrackingRecord(ctx context.Context) (Tracking, error) {
	row := q.db.QueryRowContext(ctx, insertTrackingRecord)
	var i Tracking
	err := row.Scan(
		&i.ID,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
